apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-python-app
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/ta213/my-python-app.git
      ref: main
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: my-python-app:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
    - type: GitHub
      github:
        secret: mygithubsecret123
