apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
  annotations:
    image.openshift.io/triggers: |
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "my-python-app:latest"
          },
          "fieldPath": "spec.template.spec.containers[?(@.name==\"my-python-app\")].image"
        }
      ]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
        - name: my-python-app
          image: image-registry.openshift-image-registry.svc:5000/test-build/my-python-app:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
